# Generated by Django 5.0.14 on 2026-10-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refund_needed', 'Paid — refund needed')], default='pending', max_length=20),
        ),
    ]
